Added a note to a current bug
SAP-docs/sapui5 pull request #43
Opened 2023-02-28 09:22 UTC by John-H-Smith

If using a line item criticality with a qualifier, at least one field without a qualifier must be included in the view to take effect. This is probably a bug, maybe should be escalated to the devs.

2023-02-28 10:01 UTC, KvM2 commented
Hi @John-H-Smith , thanks for your contribution. We appreciate it and will look into this.

2023-03-03 15:28 UTC, JannaLisa commented
Hello @John-H-Smith ,
I'm still waiting for a response from my team on this. Will let you know as soon as I have an answer.

2023-03-06 11:22 UTC, GwendalMoreau commented
@John-H-Smith : this seems to be a bug and should be treated as such (and not a a note in the documentation). Could you share your use case or raise a ticket?

2023-03-06 11:23 UTC, GwendalMoreau requested changes
@John-H-Smith : this seems to be a bug and should be treated as such (and not a a note in the documentation). Could you share your use case or raise a ticket?

2023-03-06 11:38 UTC, John-H-Smith commented
Hi @GwendalMoreau ,
Alright, I will share my use case.
I created a cds view entity in the backend with associations to a child view.
As those child view should be on a own table in the object page, I've set a qualifier on all fields and the view and even the line criticality. But the line item criticality wasn't shown on the table, so I added (in trial) a field without any qualifiers. And then, the criticality was shown.

2023-03-10 15:03 UTC, GwendalMoreau commented
@John-H-Smith : could you share your application metadata?

2023-05-02 11:27 UTC, OlMue commented
Hi @John-H-Smith, could please give @GwendalMoreau some information on the metadata? Thank you! :-)

2023-05-30 13:06 UTC, OlMue commented
Hi there 👋 There's been no activity on this issue for a while, so we're closing it. If you've further information to provide, please comment below and add that information. We'll review it and reopen the conversation if necessary. Until next time, thanks!

2023-05-30 13:06 UTC, closed without merging